### ISSUE TITLE
Python 3.12.3 internal error

### ISSUE THREAD

**Issue by Valiantsin2021** [olgapavlova/pytest-oneline#1]
вылетает с ошибкой

INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "C:\testing_frameworks\Python\API testing airports\venv\Lib\site-packages\_pytest\main.py", line 267, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "C:\testing_frameworks\Python\API testing airports\venv\Lib\site-packages\_pytest\config\__init__.py", line 1053, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "C:\testing_frameworks\Python\API testing airports\venv\Lib\site-packages\pluggy\_hooks.py", line 514, in call_historic        
INTERNALERROR>     res = self._hookexec(self.name, self._hookimpls, kwargs, False)
INTERNALERROR>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "C:\testing_frameworks\Python\API testing airports\venv\Lib\site-packages\pluggy\_manager.py", line 115, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "C:\testing_frameworks\Python\API testing airports\venv\Lib\site-packages\pluggy\_callers.py", line 113, in _multicall
INTERNALERROR>     raise exception.with_traceback(exception.__traceback__)
INTERNALERROR>   File "C:\testing_frameworks\Python\API testing airports\venv\Lib\site-packages\pluggy\_callers.py", line 77, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>           ^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "C:\testing_frameworks\Python\API testing airports\tests\conftest.py", line 16, in pytest_configure
INTERNALERROR>     OneLineState(config)
INTERNALERROR>   File "C:\testing_frameworks\Python\API testing airports\tests\conftest.py", line 106, in __init__
INTERNALERROR>     self.v = config.get_verbosity()
INTERNALERROR>              ^^^^^^^^^^^^^^^^^^^^
INTERNALERROR> AttributeError: 'Config' object has no attribute 'get_verbosity'

**Comment by olgapavlova** [comment]
Какой версией pytest Вы пользуетесь?
Метод get_verbosity появился в классе Config начиная с версии 8.0.
В версии 7.4 и ниже этого метода нет.

**Comment by Valiantsin2021** [comment]
7.4.3, :) мой недосмотр. С версией 8.3.3 все работает, но при использовании allure получаем немного каши в логе.

**Comment by olgapavlova** [comment]
Когда обновитесь до 8.0 или выше — напишите, пожалуйста, исчезла ли проблема.
Ну или можно руками заменить вызов этой функции на такой код: ```bool(config.getoption("v"))``` — ближайший эквивалент.
